import type { PermissionCode, PolicyCode } from '../../permissions/index.js';
import type { z } from 'zod';

import { ReasonRequestSchema } from '../common.js';
import { buildContentOpenApiDocument } from './openapi.js';
import {
  BlockLockResponseSchema,
  BriefListQuerySchema,
  BriefPageSchema,
  BriefResponseSchema,
  CompareVersionQuerySchema,
  ContentBlockParamsSchema,
  ContentDiffResponseSchema,
  ContentPackageDetailResponseSchema,
  ContentPackagePageSchema,
  ContentPackageParamsSchema,
  ContentPackageQuerySchema,
  ContentPackageResponseSchema,
  ContentVariantDetailResponseSchema,
  ContentVariantParamsSchema,
  ContentVersionParamsSchema,
  ContentVersionResponseSchema,
  CreateBriefRequestSchema,
  CreateContentPackageRequestSchema,
  DropVariantRequestSchema,
  GenerateContentRequestSchema,
  GenerationRunParamsSchema,
  GenerationRunResponseSchema,
  LockBlockRequestSchema,
  ContentNoContentResponseSchema,
  QualityCheckRequestSchema,
  RegenerateVariantRequestSchema,
  ReopenVariantsRequestSchema,
  RollbackRequestSchema,
  UpdateBriefRequestSchema,
  UpdateVariantRequestSchema,
} from './schemas.js';

export type ContentApiMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';
export type ContentIdempotency =
  '-' | 'key+body_hash' | 'key+content_hash' | 'key+version' | 'resource+version';

export interface ContentApiContract {
  readonly bodySchema: z.ZodType | null;
  readonly idempotency: ContentIdempotency;
  readonly key: string;
  readonly method: ContentApiMethod;
  readonly paramsSchema: z.ZodType | null;
  readonly path: string;
  readonly permission: Extract<
    PermissionCode,
    | 'content.briefs.manage'
    | 'content.production.manage'
    | 'content.read'
    | 'review.decide'
    | 'tenant.workspaces.manage'
  >;
  readonly policy: Extract<
    PolicyCode,
    | 'content_editor_or_admin'
    | 'reviewer_or_admin'
    | 'strategy_or_content_editor_or_admin'
    | 'tenant_admin_or_owner'
    | 'tenant_member'
  >;
  readonly querySchema: z.ZodType | null;
  readonly requestName: string;
  readonly responseName: string;
  readonly responseSchema: z.ZodType;
  readonly successStatus: 200 | 201 | 202 | 204;
}

const contracts = [
  contract(
    'brief.create',
    'POST',
    '/briefs',
    'strategy_or_content_editor_or_admin',
    'content.briefs.manage',
    'key+body_hash',
    CreateBriefRequestSchema,
    null,
    null,
    'CreateBriefRequest',
    'BriefView',
    BriefResponseSchema,
    201,
  ),
  contract(
    'brief.list',
    'GET',
    '/briefs',
    'tenant_member',
    'content.read',
    '-',
    null,
    null,
    BriefListQuerySchema,
    'BriefListQuery',
    'BriefPage',
    BriefPageSchema,
    200,
  ),
  contract(
    'brief.get',
    'GET',
    '/briefs/{id}',
    'tenant_member',
    'content.read',
    '-',
    null,
    ContentPackageParamsSchema,
    null,
    '-',
    'BriefView',
    BriefResponseSchema,
    200,
  ),
  contract(
    'brief.update',
    'PATCH',
    '/briefs/{id}',
    'strategy_or_content_editor_or_admin',
    'content.briefs.manage',
    'key+version',
    UpdateBriefRequestSchema,
    ContentPackageParamsSchema,
    null,
    'UpdateBriefRequest',
    'BriefView',
    BriefResponseSchema,
    200,
  ),
  contract(
    'package.create',
    'POST',
    '/content-packages',
    'content_editor_or_admin',
    'content.production.manage',
    'key+body_hash',
    CreateContentPackageRequestSchema,
    null,
    null,
    'CreateContentPackageRequest',
    'ContentPackageView',
    ContentPackageResponseSchema,
    201,
  ),
  contract(
    'package.list',
    'GET',
    '/content-packages',
    'tenant_member',
    'content.read',
    '-',
    null,
    null,
    ContentPackageQuerySchema,
    'ContentPackageQuery',
    'ContentPackagePage',
    ContentPackagePageSchema,
    200,
  ),
  contract(
    'package.get',
    'GET',
    '/content-packages/{id}',
    'tenant_member',
    'content.read',
    '-',
    null,
    ContentPackageParamsSchema,
    null,
    '-',
    'ContentPackageDetail',
    ContentPackageDetailResponseSchema,
    200,
  ),
  contract(
    'package.generate',
    'POST',
    '/content-packages/{id}/generate',
    'content_editor_or_admin',
    'content.production.manage',
    'key+body_hash',
    GenerateContentRequestSchema,
    ContentPackageParamsSchema,
    null,
    'GenerateContentRequest',
    'GenerationRunView',
    GenerationRunResponseSchema,
    202,
  ),
  contract(
    'package.abandon',
    'POST',
    '/content-packages/{id}/abandon',
    'content_editor_or_admin',
    'content.production.manage',
    'resource+version',
    ReasonRequestSchema,
    ContentPackageParamsSchema,
    null,
    'ReasonRequest',
    'ContentPackageView',
    ContentPackageResponseSchema,
    200,
  ),
  contract(
    'package.archive',
    'POST',
    '/content-packages/{id}/archive',
    'tenant_admin_or_owner',
    'tenant.workspaces.manage',
    'resource+version',
    ReasonRequestSchema,
    ContentPackageParamsSchema,
    null,
    'ReasonRequest',
    'ContentPackageView',
    ContentPackageResponseSchema,
    200,
  ),
  contract(
    'package.reopen',
    'POST',
    '/content-packages/{id}/reopen',
    'reviewer_or_admin',
    'review.decide',
    'key+version',
    ReopenVariantsRequestSchema,
    ContentPackageParamsSchema,
    null,
    'ReopenVariantsRequest',
    'ContentPackageDetail',
    ContentPackageDetailResponseSchema,
    200,
  ),
  contract(
    'run.get',
    'GET',
    '/generation-runs/{id}',
    'content_editor_or_admin',
    'content.production.manage',
    '-',
    null,
    GenerationRunParamsSchema,
    null,
    '-',
    'GenerationRunView',
    GenerationRunResponseSchema,
    200,
  ),
  contract(
    'run.cancel',
    'POST',
    '/generation-runs/{id}/cancel',
    'content_editor_or_admin',
    'content.production.manage',
    'resource+version',
    ReasonRequestSchema,
    GenerationRunParamsSchema,
    null,
    'ReasonRequest',
    'GenerationRunView',
    GenerationRunResponseSchema,
    200,
  ),
  contract(
    'version.get',
    'GET',
    '/content-versions/{id}',
    'tenant_member',
    'content.read',
    '-',
    null,
    ContentVersionParamsSchema,
    null,
    '-',
    'ContentVersionView',
    ContentVersionResponseSchema,
    200,
  ),
  contract(
    'version.diff',
    'GET',
    '/content-versions/{id}/diff',
    'tenant_member',
    'content.read',
    '-',
    null,
    ContentVersionParamsSchema,
    CompareVersionQuerySchema,
    'CompareVersionQuery',
    'ContentDiffView',
    ContentDiffResponseSchema,
    200,
  ),
  contract(
    'version.rollback',
    'POST',
    '/content-versions/{id}/rollback',
    'content_editor_or_admin',
    'content.production.manage',
    'key+version',
    RollbackRequestSchema,
    ContentVersionParamsSchema,
    null,
    'RollbackRequest',
    'ContentVersionView',
    ContentVersionResponseSchema,
    200,
  ),
  contract(
    'variant.get',
    'GET',
    '/content-variants/{id}',
    'tenant_member',
    'content.read',
    '-',
    null,
    ContentVariantParamsSchema,
    null,
    '-',
    'ContentVariantDetail',
    ContentVariantDetailResponseSchema,
    200,
  ),
  contract(
    'variant.update',
    'PATCH',
    '/content-variants/{id}',
    'content_editor_or_admin',
    'content.production.manage',
    'key+version',
    UpdateVariantRequestSchema,
    ContentVariantParamsSchema,
    null,
    'UpdateVariantRequest',
    'ContentVariantDetail',
    ContentVariantDetailResponseSchema,
    200,
  ),
  contract(
    'block.lock',
    'POST',
    '/content-variants/{id}/blocks/{blockId}/lock',
    'content_editor_or_admin',
    'content.production.manage',
    'resource+version',
    LockBlockRequestSchema,
    ContentBlockParamsSchema,
    null,
    'LockBlockRequest',
    'BlockLockView',
    BlockLockResponseSchema,
    201,
  ),
  contract(
    'block.unlock',
    'DELETE',
    '/content-variants/{id}/blocks/{blockId}/lock',
    'content_editor_or_admin',
    'content.production.manage',
    'resource+version',
    null,
    ContentBlockParamsSchema,
    null,
    '-',
    '-',
    ContentNoContentResponseSchema,
    204,
  ),
  contract(
    'variant.quality-check',
    'POST',
    '/content-variants/{id}/quality-check',
    'content_editor_or_admin',
    'content.production.manage',
    'key+content_hash',
    QualityCheckRequestSchema,
    ContentVariantParamsSchema,
    null,
    'QualityCheckRequest',
    'GenerationRunView',
    GenerationRunResponseSchema,
    202,
  ),
  contract(
    'variant.regenerate',
    'POST',
    '/content-variants/{id}/regenerate',
    'content_editor_or_admin',
    'content.production.manage',
    'key+body_hash',
    RegenerateVariantRequestSchema,
    ContentVariantParamsSchema,
    null,
    'RegenerateVariantRequest',
    'GenerationRunView',
    GenerationRunResponseSchema,
    202,
  ),
  contract(
    'variant.drop',
    'POST',
    '/content-variants/{id}/drop',
    'content_editor_or_admin',
    'content.production.manage',
    'resource+version',
    DropVariantRequestSchema,
    ContentVariantParamsSchema,
    null,
    'DropVariantRequest',
    'ContentVariantDetail',
    ContentVariantDetailResponseSchema,
    200,
  ),
] as const satisfies readonly ContentApiContract[];

export const CONTENT_API_CONTRACTS: readonly ContentApiContract[] = Object.freeze(contracts);
export type ContentApiContractKey = (typeof contracts)[number]['key'];
export const CONTENT_OPENAPI_DOCUMENT = buildContentOpenApiDocument(CONTENT_API_CONTRACTS);

export function findContentApiContract(key: ContentApiContractKey): ContentApiContract {
  const found = contracts.find((candidate) => candidate.key === key);
  if (!found) throw new Error(`Unknown Content API contract: ${key}`);
  return found;
}

function contract(
  key: string,
  method: ContentApiMethod,
  path: string,
  policy: ContentApiContract['policy'],
  permission: ContentApiContract['permission'],
  idempotency: ContentIdempotency,
  bodySchema: z.ZodType | null,
  paramsSchema: z.ZodType | null,
  querySchema: z.ZodType | null,
  requestName: string,
  responseName: string,
  responseSchema: z.ZodType,
  successStatus: ContentApiContract['successStatus'],
): ContentApiContract {
  return {
    bodySchema,
    idempotency,
    key,
    method,
    paramsSchema,
    path,
    permission,
    policy,
    querySchema,
    requestName,
    responseName,
    responseSchema,
    successStatus,
  };
}

export * from './schemas.js';
export * from './openapi.js';
