import { z } from 'zod';

import { ReasonRequestSchema } from '../common.js';
import {
  CreateProjectRequestSchema,
  ProjectIdSchema,
  ProjectListQuerySchema,
  ProjectPageSchema,
  ProjectResponseSchema,
  UpdateProjectRequestSchema,
} from '../projects.js';
import {
  CreateWorkspaceRequestSchema,
  UpdateWorkspaceRequestSchema,
  WorkspaceIdSchema,
  WorkspaceListQuerySchema,
  WorkspacePageSchema,
  WorkspaceResponseSchema,
} from '../workspaces.js';
import { InvitationIdSchema } from '../memberships/schemas.js';
import {
  AcceptInvitationRequestSchema,
  ChangePasswordRequestSchema,
  ForgotPasswordRequestSchema,
  InvitationTokenSchema,
  LoginRequestSchema,
  ResetPasswordRequestSchema,
  SessionResponseSchema,
  SupportGrantRequestSchema,
  SupportGrantResponseSchema,
  SwitchTenantRequestSchema,
  TenantChoiceListResponseSchema,
  TenantResponseSchema,
  UpdateTenantRequestSchema,
} from './schemas.js';

export * from './schemas.js';

export interface CoreApiContract {
  readonly bodySchema: z.ZodType | null;
  readonly idempotency: string;
  readonly key: string;
  readonly method: 'DELETE' | 'GET' | 'PATCH' | 'POST';
  readonly paramsSchema: z.ZodType | null;
  readonly path: string;
  readonly permission: string;
  readonly policy: string;
  readonly querySchema: z.ZodType | null;
  readonly responseName: string;
  readonly responseSchema: z.ZodType | null;
  readonly security: 'public' | 'session' | 'session_csrf';
  readonly successStatus: number;
}

const UuidParamsSchema = z.object({ id: WorkspaceIdSchema }).strict();
const InvitationTokenParamsSchema = z.object({ token: InvitationTokenSchema }).strict();

const contracts: readonly CoreApiContract[] = [
  c(
    'auth.login',
    'POST',
    '/auth/login',
    'public',
    '-',
    LoginRequestSchema,
    null,
    SessionResponseSchema,
    'SessionView',
    200,
  ),
  c(
    'auth.logout',
    'POST',
    '/auth/logout',
    'authenticated',
    'session',
    null,
    null,
    null,
    'NoContent',
    204,
  ),
  c(
    'auth.session',
    'GET',
    '/auth/session',
    'authenticated',
    '-',
    null,
    null,
    SessionResponseSchema,
    'SessionView',
    200,
  ),
  c(
    'auth.tenants',
    'GET',
    '/auth/tenants',
    'authenticated',
    '-',
    null,
    null,
    TenantChoiceListResponseSchema,
    'TenantChoice[]',
    200,
  ),
  c(
    'auth.switch-tenant',
    'POST',
    '/auth/switch-tenant',
    'authenticated',
    'key+body_hash',
    SwitchTenantRequestSchema,
    null,
    SessionResponseSchema,
    'SessionView',
    200,
  ),
  c(
    'auth.password.forgot',
    'POST',
    '/auth/password/forgot',
    'public',
    '-',
    ForgotPasswordRequestSchema,
    null,
    null,
    'Accepted',
    202,
  ),
  c(
    'auth.password.reset',
    'POST',
    '/auth/password/reset',
    'public',
    'token',
    ResetPasswordRequestSchema,
    null,
    null,
    'NoContent',
    204,
  ),
  c(
    'auth.password.change',
    'POST',
    '/auth/password/change',
    'authenticated',
    'key+body_hash',
    ChangePasswordRequestSchema,
    null,
    null,
    'NoContent',
    204,
  ),
  c(
    'invitations.accept',
    'POST',
    '/invitations/{token}/accept',
    'public',
    'token',
    AcceptInvitationRequestSchema,
    null,
    SessionResponseSchema,
    'SessionView',
    200,
    InvitationTokenParamsSchema,
  ),
  c(
    'invitations.revoke',
    'DELETE',
    '/invitations/{id}',
    'tenant.members.manage',
    'resource+version',
    null,
    null,
    null,
    'NoContent',
    204,
    z.object({ id: InvitationIdSchema }).strict(),
    'tenant_admin_or_owner',
  ),
  c(
    'platform.support-access-grants.create',
    'POST',
    '/platform/support-access-grants',
    'platform.support_access.manage',
    'key+body_hash',
    SupportGrantRequestSchema,
    null,
    SupportGrantResponseSchema,
    'SupportGrantView',
    201,
    null,
    'platform_admin',
  ),
  c(
    'tenant.get',
    'GET',
    '/tenant',
    'tenant.profile.read',
    '-',
    null,
    null,
    TenantResponseSchema,
    'TenantView',
    200,
    null,
    'tenant_member',
  ),
  c(
    'tenant.update',
    'PATCH',
    '/tenant',
    'tenant.profile.manage',
    'key+version',
    UpdateTenantRequestSchema,
    null,
    TenantResponseSchema,
    'TenantView',
    200,
    null,
    'tenant_owner',
  ),
  c(
    'workspaces.create',
    'POST',
    '/workspaces',
    'tenant.workspaces.manage',
    'key+body_hash',
    CreateWorkspaceRequestSchema,
    null,
    WorkspaceResponseSchema,
    'WorkspaceView',
    201,
    null,
    'tenant_admin_or_owner',
  ),
  c(
    'workspaces.list',
    'GET',
    '/workspaces',
    'tenant.workspaces.read',
    '-',
    null,
    WorkspaceListQuerySchema,
    WorkspacePageSchema,
    'WorkspacePage',
    200,
    null,
    'tenant_member',
  ),
  c(
    'workspaces.get',
    'GET',
    '/workspaces/{id}',
    'tenant.workspaces.read',
    '-',
    null,
    null,
    WorkspaceResponseSchema,
    'WorkspaceView',
    200,
    UuidParamsSchema,
    'tenant_member',
  ),
  c(
    'workspaces.update',
    'PATCH',
    '/workspaces/{id}',
    'tenant.workspaces.manage',
    'key+version',
    UpdateWorkspaceRequestSchema,
    null,
    WorkspaceResponseSchema,
    'WorkspaceView',
    200,
    UuidParamsSchema,
    'tenant_admin_or_owner',
  ),
  c(
    'workspaces.archive',
    'POST',
    '/workspaces/{id}/archive',
    'tenant.workspaces.manage',
    'resource+version',
    ReasonRequestSchema,
    null,
    WorkspaceResponseSchema,
    'WorkspaceView',
    200,
    UuidParamsSchema,
    'tenant_admin_or_owner',
  ),
  c(
    'projects.create',
    'POST',
    '/projects',
    'strategy.manage',
    'key+body_hash',
    CreateProjectRequestSchema,
    null,
    ProjectResponseSchema,
    'ProjectView',
    201,
    null,
    'strategy_editor_or_admin',
  ),
  c(
    'projects.list',
    'GET',
    '/projects',
    'strategy.read',
    '-',
    null,
    ProjectListQuerySchema,
    ProjectPageSchema,
    'ProjectPage',
    200,
    null,
    'tenant_member',
  ),
  c(
    'projects.get',
    'GET',
    '/projects/{id}',
    'strategy.read',
    '-',
    null,
    null,
    ProjectResponseSchema,
    'ProjectView',
    200,
    z.object({ id: ProjectIdSchema }).strict(),
    'tenant_member',
  ),
  c(
    'projects.update',
    'PATCH',
    '/projects/{id}',
    'strategy.manage',
    'key+version',
    UpdateProjectRequestSchema,
    null,
    ProjectResponseSchema,
    'ProjectView',
    200,
    z.object({ id: ProjectIdSchema }).strict(),
    'strategy_editor_or_admin',
  ),
];

export const CORE_API_CONTRACTS = Object.freeze(
  contracts.map((contract) => Object.freeze(contract)),
);

function c(
  key: string,
  method: CoreApiContract['method'],
  path: string,
  permission: string,
  idempotency: string,
  bodySchema: z.ZodType | null,
  querySchema: z.ZodType | null,
  responseSchema: z.ZodType | null,
  responseName: string,
  successStatus: number,
  paramsSchema: z.ZodType | null = null,
  policy = permission,
): CoreApiContract {
  const security =
    permission === 'public' ? 'public' : method === 'GET' ? 'session' : 'session_csrf';
  return {
    bodySchema,
    idempotency,
    key,
    method,
    paramsSchema,
    path,
    permission,
    policy,
    querySchema,
    responseName,
    responseSchema,
    security,
    successStatus,
  };
}
