export const PUBLISHING_ACCOUNT_CONNECTOR = Symbol('PUBLISHING_ACCOUNT_CONNECTOR');
export const PUBLISHING_CREDENTIALS = Symbol('PUBLISHING_CREDENTIALS');
export const PUBLISHING_STORAGE = Symbol('PUBLISHING_STORAGE');
